### ISSUE TITLE
inventory example for single

### ISSUE THREAD

**Issue by patsevanton** [VictoriaMetrics/ansible-playbooks#16]
Hello! Thanks for role victoriametrics
Could you publish inventory example for single?

**Comment by zekker6** [comment]
Hello!
VM-single installation can be used without modifying defaults as it has much simpler architecture than cluster installation.
Your inventory might be similar to the following:
```ini
[all]
vm-single ansible_host=x.x.x.x
```

You can find defaults [here](https://github.com/VictoriaMetrics/ansible-playbooks/blob/master/roles/single/defaults/main.yml)

Short readme with description of defaults is available [here](https://github.com/VictoriaMetrics/ansible-playbooks/tree/master/roles/single)
