### ISSUE TITLE
Link to ansible galaxy is broken

### ISSUE THREAD

**Issue by bluepuma77** [VictoriaMetrics/ansible-playbooks#50]
It seems the link has changed, it currently leads to a start page.

> Roles are published in ansible galaxy: https://galaxy.ansible.com/victoriametrics

**Comment by zekker6** [comment]
@bluepuma77 Thank you for noticing! 
https://github.com/VictoriaMetrics/ansible-playbooks/commit/9edefc7a6ae204fe2307cae34c58e0f090206eb7 fixes a link to the correct one: https://galaxy.ansible.com/ui/namespaces/victoriametrics/
