### ISSUE TITLE
No log for passwords

### ISSUE THREAD

**Issue by kkrasnov1** [VictoriaMetrics/ansible-playbooks#65]
Hi,
Please add no_log: true to task "Template auth config" in roles/vmauth/tasks/configure.yml because it may contain sensitive information.

**Comment by zekker6** [comment]
Hi @kkrasnov1 
This was added as a part of [v0.58.1](https://github.com/VictoriaMetrics/ansible-playbooks/releases/tag/v0.58.1) release.
Closing as completed.
